services:
  gnat_yaf:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_yaf
    restart: unless-stopped      
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_nice
    environment:
      - GNAT_INTERFACE=${GNAT_INTERFACE}
      - GNAT_OBSERVATION_TAG=${GNAT_OBSERVATION_TAG}  
      - GNAT_OUTPUT_DIR=/var/spool/${GNAT_OBSERVATION_TAG}
      - GNAT_EXPORT_INTERVAL=20
    volumes:
      - ./var/spool:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_yaf.sh

  gnat_import:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_import
    restart: unless-stopped   
    environment:   
      - GNAT_OPTIONS="observation=${GNAT_OBSERVATION_TAG}""
      - GNAT_INPUT_DIR=/var/spool/yaf
      - GNAT_OUTPUT_DIR=/var/spool/flow
      - GNAT_PROCESSED_DIR=/var/spool/imported  
    volumes:
      - ./var/spool:/var/spool  
      - ./var/maxmind:/var/maxmind:ro          
    depends_on:
      - gnat_db
    command: /opt/gnat/scripts/entrypoint-gnat_import.sh
    
  gnat_batch:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_batch
    restart: unless-stopped   
    environment:   
      - GNAT_INPUT_DIR=/var/spool/flow
      - GNAT_OUTPUT_DIR=/var/spool/batch
      - GNAT_BATCH_INTERVAL=60 
    volumes:
      - ./var/spool:/var/spool      
    command: /opt/gnat/scripts/entrypoint-gnat_batch.sh

  gnat_hbos:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_hbos
    restart: unless-stopped
    environment:
      - GNAT_INPUT_DIR=/var/spool/batch
      - GNAT_OUTPUT_DIR=/var/spool/hbos
      - GNAT_PROCESSED_DIR=/var/spool/processed
      - GNAT_ANOMALY_DIR=/var/spool/anomaly
      - GNAT_MODEL_FILE=/model/hbos.model
      - GNAT_THRESHOLD=4
    volumes:
      - ./var/spool:/var/spool
      - ./var/model:/model
    command: /opt/gnat/scripts/entrypoint-gnat_hbos.sh        

  gnat_db:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_db
    restart: unless-stopped   
    environment:
      - GNAT_INPUT_DIR=/var/spool/hbos
      - GNAT_PROCESSED_DIR=/var/spool/processed
      - GNAT_QDB_HOST=${GNAT_QDB_HOST}
      - GNAT_QDB_RETENTION=${GNAT_QDB_RETENTION}            
    volumes:
     - ./var/spool:/var/spool  
    depends_on:
      - questdb 
    command: /opt/gnat/scripts/entrypoint-gnat_db.sh

  gnat_proxy:
    image: fidelismachine/galileo_proxy:latest
    container_name: gnat_nginx
    restart: unless-stopped 
    volumes:
      - ./var/log/nginx:/var/log/nginx
      # uncomment below to enable signed certificates
      #- ./ssl.crt:/etc/nginx/ssl.crt
      #- ./ssl.key:/etc/nginx/ssl.key      
    ports:
      - 80:80/tcp
      - 443:443/tcp

  gnat_dashboard:
    image: fidelismachine/galileo_dashboard:latest
    container_name: gnat_dashboard
    restart: unless-stopped    
    environment:
      - "TZ=UTC"
    user: "0:0"
    volumes:
      - ./var/grafana:/var/lib/grafana

  questdb:
    image: questdb/questdb
    container_name: questdb
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./var/questdb:/root/.questdb
    environment:
      - QDB_HTTP_ENABLED=true           
      - QDB_LOG_W_STDOUT_LEVEL=ERROR
      - QDB_LOG_W_FILE_LEVEL=ERROR
      - QDB_LOG_W_HTTP_MIN_LEVEL=ERROR
      - QDB_SHARED_WORKER_COUNT=4        # Amount of worker threads
      - QDB_PG_USER=${GNAT_QDB_USERNAME}     # postgresql user -> Configured in .env file
      - QDB_PG_PASSWORD=${GNAT_QDB_PASSWORD} # postgresql password -> Configured in .env file
      - QDB_TELEMETRY_ENABLED=false      # Disable telemetry
      - QDB_HTTP_SECURITY_READONLY=false
      - QBD_LINE_UDP_ENABLED=false
      - QDB_HTTP_MIN_ENABLED=true

