services:
  gnat_yaf:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_yaf
    restart: unless-stopped      
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_nice
    environment:
      - GNAT_INTERFACE=${GNAT_INTERFACE}
      - GNAT_OBSERVATION_TAG=${GNAT_OBSERVATION_TAG}  
      - GNAT_OUTPUT_DIR=/var/spool/${GNAT_OBSERVATION_TAG}
      - GNAT_EXPORT_INTERVAL=20
    volumes:
      - ./var/spool:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_yaf.sh

  gnat_import:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_import
    restart: unless-stopped   
    environment:   
      - GNAT_OBSERVATION_TAG=${GNAT_OBSERVATION_TAG}
      - GNAT_INPUT_DIR=/var/spool/${GNAT_OBSERVATION_TAG}
      - GNAT_OUTPUT_DIR=/var/spool/flow
      - GNAT_PROCESSED_DIR=/var/spool/imported  
    volumes:
      - ./var/spool:/var/spool  
      - ./var/maxmind:/var/maxmind:ro          
    command: /opt/gnat/scripts/entrypoint-gnat_import.sh
   
   