services:
  # GNAT - Galileo Network Analysis Toolkit
  # This is a simple example of how to run GNAT using Docker Compose.
  # It assumes you have the galileo_toolkit image available locally or in a registry.
  # GNAT is designed to run on a host network, so it uses network_mode: host.
  # It also requires specific capabilities to be added for network monitoring.
  # The GNAT_INTERFACE and GNAT_OBSERVATION_TAG environment variables must be set in your .env file.
  # The GNAT_INTERFACE is the network interface to monitor (e.g., eth0, wlan0).
  # The GNAT_OBSERVATION_TAG is a unique identifier for the observation, used to organize output files.
  # The volumes are mounted to /var/spool/gnat to exchange data across containers.


  gnat_yaf:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_yaf
    restart: unless-stopped
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
      - sys_nice
    environment:
      GNAT_INTERFACE: ${GNAT_INTERFACE}
      GNAT_OBSERVATION_TAG: ${GNAT_OBSERVATION_TAG}
      GNAT_OUTPUT_DIR: /var/spool/${GNAT_OBSERVATION_TAG}
      GNAT_EXPORT_INTERVAL: 20
    volumes:
      - /var/spool/gnat:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_yaf.sh

  # GNAT Importer and Batch Processors
  # --------------------------------------------------------------------------
  # These containers process the data collected by gnat_yaf.
  # gnat_import imports the data from the observation directory.
  # gnat_minute, gnat_hour, and gnat_day process the data in batches at different intervals.
  # They read from the previous output directory and write to the next one.
  # Ensure that the GNAT_INPUT_DIR and GNAT_OUTPUT_DIR environment variables are set correctly.
  # The GNAT_INTERVAL environment variable defines the processing interval (minute, hour, day).
  # The TZ environment variable sets the timezone for the processing.
  # Make sure to create the /var/spool/gnat directory on your host machine before running this compose file.
  # The /var/spool/gnat directory is used to store the data exchanged between containers.
  gnat_import:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_import
    restart: unless-stopped
    environment:  
      GNAT_INPUT_DIR: /var/spool/${GNAT_OBSERVATION_TAG}
      GNAT_OUTPUT_DIR: /var/spool/import
    volumes:
      - /var/spool/gnat:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_import.sh

gnat_minute:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_minute
    restart: unless-stopped
    environment:
      GNAT_INPUT_DIR: /var/spool/import
      GNAT_OUTPUT_DIR: /var/spool/minute
      GNAT_INTERVAL: minute
      TZ: UTC
    volumes:
      - /var/spool/gnat:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_batch.sh

  gnat_hour:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_hour
    restart: unless-stopped
    environment:
      GNAT_INPUT_DIR: /var/spool/minute
      GNAT_OUTPUT_DIR: /var/spool/hour
      GNAT_INTERVAL: hour
      TZ: UTC
    volumes:
      - /var/spool/gnat:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_batch.sh

  gnat_day:
    image: fidelismachine/galileo_toolkit:latest
    container_name: gnat_day
    restart: unless-stopped
    environment:
      GNAT_INPUT_DIR: /var/spool/hour
      GNAT_OUTPUT_DIR: /var/spool/day
      GNAT_INTERVAL: day
      TZ: UTC
    volumes:
      - /var/spool/gnat:/var/spool
    command: /opt/gnat/scripts/entrypoint-gnat_batch.sh
